### PR TITLE
filter nil sort key items out of prev/next

### PR DESCRIPTION
**Pull request by seancorfield**
I believe this addresses #163 in the most intuitive manner:
* pages without `:page-index` do not get prev/next
* pages with `:page-index` do not get prev (or next) if that prev (or next) page does not have `:page-index`
This prevents fragmented prev/next at the transition between (sorted) pages with/without `:page-index`

The same filtering is provided for posts without `:date` for consistency (but I don't think that's actually possible, right?).

### CODE REVIEW

**Review by yogthos — APPROVED** [review]

**Comment by yogthos** [comment]
I don't think so either, but agree makes sense to keep it consistent. I'll take a look at doing a release tomorrow morning.

**Comment by yogthos** [comment]
and new version's up on Clojars

**Comment by seancorfield** [comment]
Updated both my sites based on Cryogen to 0.4.3, regenerated and pushed them and they look good -- thank you!

**Comment by yogthos** [comment]
Great to hear, and thanks for doing the pr. :)

**Pull request merged**
