### PR TITLE
Support clean urls by removing html extension

### PR DESCRIPTION
**Pull request by devth**
Fixes https://github.com/cryogen-project/cryogen/issues/166

### CODE REVIEW

**Comment by devth** [comment]
@lacarmen would love to get this released when you get a chance! Thanks!

**Comment by lacarmen** [comment]
@devth just released the change as version 0.1.65. Let me know if it's working for you!

**Comment by devth** [comment]
Thanks! I'll try it out shortly.

**Comment by devth** [comment]
Yesssssssssss https://yetibot.com/user-guide so clean!

**Comment by lacarmen** [comment]
Woohoo!

**Comment by luchiniatwork** [comment]
Folks... for some reason once I bumped to 1.66 I lost the ability to have `path/index.html` that `clean-urls?` used to give. I wonder if this is something reported.

With very superficial investigation I landed on this PR.

**Pull request merged**
