### PR TITLE
Add author and (short) description for RSS

### PR DESCRIPTION
**Pull request by tomasz-biernacki**
I'm able to add to the post metadata information about the author and a short description of the post, and then use this information in the HTML template (following this [simple approach](https://github.com/cryogen-project/cryogen/issues/30))

Now, I'd also like to have this information in the RSS and this PR is about adding those two values. The author is simply the author, while the description can be either the description specified in the post metadata or the content of the post. This also fit the [specification](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt): "_...if so its description is a synopsis of the story, and the link points to the full story. An item may also be complete in itself, if so, the description contains the text (entity-encoded HTML is allowed), ..._"

What do you think?

### CODE REVIEW

**Comment by lacarmen** [comment]
Looks good :)

**Comment by tomasz-biernacki** [comment]
@lacarmen Thanks a lot ;)
Are you also planning to update the version and get it deployed on Clojars?

**Comment by lacarmen** [comment]
I just pushed 0.1.35 out :)

**Comment by tomasz-biernacki** [comment]
Thanks :)

**Pull request merged**
